// based on KNLMeansCL by Khanattila

#include <VSHelper4.h>
#include <VapourSynth4.h>
#include <algorithm>
#include <array>
#include <config.h> // generated by cmake and git
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <limits>
#include <memory>
#include <mutex>
#include <nlm_ispc.h> // generated by the ispc compiler
#include <shared_mutex>
#include <string_view>
#include <thread>
#include <type_traits>
#include <unordered_map>

namespace {
enum struct ChannelMode : std::uint8_t { Y, UV, YUV, RGB };

struct NLMData {
    VSNode* node = nullptr; // clip
    const VSVideoInfo* vi = nullptr;
    int d = 0;
    int a = 0;
    int s = 0;
    float h = 0.0f;
    float h2_inv_norm = 0.0f;
    ChannelMode channels = ChannelMode::Y;
    decltype(&ispc::nlmVerticalWelsch) nlm_vertical = nullptr; // wmode
    float wref = 0.0f;
    VSNode* ref_node = nullptr; // rclip

    // run-time resources
    std::shared_mutex workspaces_lock;
    std::unordered_map<std::thread::id, float*> workspaces;
};
} // namespace

template <typename T> [[nodiscard]] static inline auto castVoidPtr(T* p) noexcept {
    if constexpr (std::is_const_v<T>) {
        return reinterpret_cast<const void*>(p);
    } else {
        return reinterpret_cast<void*>(p);
    }
}

template <typename T1, typename T2>
[[nodiscard]] static inline std::array<T1*, 3> castPtrs(std::array<T2*, 3> ptrs) noexcept {
    return {
        reinterpret_cast<T1*>(ptrs[0]),
        reinterpret_cast<T1*>(ptrs[1]),
        reinterpret_cast<T1*>(ptrs[2]),
    };
}

template <typename T> static inline constexpr T square(T x) noexcept {
    return x * x;
}

// T: (const) VSFrameRef
template <typename T> static inline auto getPtrs(T* frame, ChannelMode channels, const VSAPI* vsapi) noexcept {

    using value_type = std::conditional_t<std::is_const_v<T>, const void, void>;

    std::array<value_type*, 3> ptrs{};

    auto get_ptr = [frame, vsapi](int plane) {
        if constexpr (std::is_const_v<T>) {
            return castVoidPtr(vsapi->getReadPtr(frame, plane));
        } else {
            return castVoidPtr(vsapi->getWritePtr(frame, plane));
        }
    };

    switch (channels) {
    case ChannelMode::Y:
        ptrs[0] = get_ptr(0);
        break;
    case ChannelMode::UV:
        ptrs[1] = get_ptr(1);
        ptrs[2] = get_ptr(2);
        break;
    case ChannelMode::YUV:
    case ChannelMode::RGB:
        ptrs[0] = get_ptr(0);
        ptrs[1] = get_ptr(1);
        ptrs[2] = get_ptr(2);
        break;
    }

    return ptrs;
}

static inline void nlmDistanceDispatch_f32(
    float* temp0,
    std::array<const float*, 3> centerp,
    std::array<const float*, 3> neighborp,
    int offset_x,
    int offset_y,
    int width,
    int height,
    int stride,
    ChannelMode channels
) noexcept {

    switch (channels) {
    case ChannelMode::Y:
        ispc::nlmDistanceLuma_f32(temp0, centerp[0], neighborp[0], offset_x, offset_y, width, height, stride);
        break;
    case ChannelMode::UV:
        ispc::nlmDistanceChroma_f32(
            temp0, centerp[1], centerp[2], neighborp[1], neighborp[2], offset_x, offset_y, width, height, stride
        );
        break;
    case ChannelMode::YUV:
        ispc::nlmDistanceYUV_f32(
            temp0,
            centerp[0],
            centerp[1],
            centerp[2],
            neighborp[0],
            neighborp[1],
            neighborp[2],
            offset_x,
            offset_y,
            width,
            height,
            stride
        );
        break;
    case ChannelMode::RGB:
        ispc::nlmDistanceRGB_f32(
            temp0,
            centerp[0],
            centerp[1],
            centerp[2],
            neighborp[0],
            neighborp[1],
            neighborp[2],
            offset_x,
            offset_y,
            width,
            height,
            stride
        );
        break;
    }
}

static inline void nlmDistanceDispatch_u8(
    float* temp0,
    std::array<const uint8_t*, 3> centerp,
    std::array<const uint8_t*, 3> neighborp,
    int offset_x,
    int offset_y,
    int width,
    int height,
    int stride,
    ChannelMode channels,
    float inv_divisor
) noexcept {

    switch (channels) {
    case ChannelMode::Y:
        ispc::nlmDistanceLuma_u8(
            temp0, centerp[0], neighborp[0], offset_x, offset_y, width, height, stride, inv_divisor
        );
        break;
    case ChannelMode::UV:
        ispc::nlmDistanceChroma_u8(
            temp0,
            centerp[1],
            centerp[2],
            neighborp[1],
            neighborp[2],
            offset_x,
            offset_y,
            width,
            height,
            stride,
            inv_divisor
        );
        break;
    case ChannelMode::YUV:
        ispc::nlmDistanceYUV_u8(
            temp0,
            centerp[0],
            centerp[1],
            centerp[2],
            neighborp[0],
            neighborp[1],
            neighborp[2],
            offset_x,
            offset_y,
            width,
            height,
            stride,
            inv_divisor
        );
        break;
    case ChannelMode::RGB:
        ispc::nlmDistanceRGB_u8(
            temp0,
            centerp[0],
            centerp[1],
            centerp[2],
            neighborp[0],
            neighborp[1],
            neighborp[2],
            offset_x,
            offset_y,
            width,
            height,
            stride,
            inv_divisor
        );
        break;
    }
}

static inline void nlmDistanceDispatch_u16(
    float* temp0,
    std::array<const uint16_t*, 3> centerp,
    std::array<const uint16_t*, 3> neighborp,
    int offset_x,
    int offset_y,
    int width,
    int height,
    int stride,
    ChannelMode channels,
    float inv_divisor
) noexcept {

    switch (channels) {
    case ChannelMode::Y:
        ispc::nlmDistanceLuma_u16(
            temp0, centerp[0], neighborp[0], offset_x, offset_y, width, height, stride, inv_divisor
        );
        break;
    case ChannelMode::UV:
        ispc::nlmDistanceChroma_u16(
            temp0,
            centerp[1],
            centerp[2],
            neighborp[1],
            neighborp[2],
            offset_x,
            offset_y,
            width,
            height,
            stride,
            inv_divisor
        );
        break;
    case ChannelMode::YUV:
        ispc::nlmDistanceYUV_u16(
            temp0,
            centerp[0],
            centerp[1],
            centerp[2],
            neighborp[0],
            neighborp[1],
            neighborp[2],
            offset_x,
            offset_y,
            width,
            height,
            stride,
            inv_divisor
        );
        break;
    case ChannelMode::RGB:
        ispc::nlmDistanceRGB_u16(
            temp0,
            centerp[0],
            centerp[1],
            centerp[2],
            neighborp[0],
            neighborp[1],
            neighborp[2],
            offset_x,
            offset_y,
            width,
            height,
            stride,
            inv_divisor
        );
        break;
    }
}

static inline void nlmDistance(
    float* temp0,
    std::array<const void*, 3> centerp,
    std::array<const void*, 3> neighborp,
    int offset_x,
    int offset_y,
    int width,
    int height,
    int stride,
    ChannelMode channels,
    int bits
) noexcept {

    if (bits == 32) {
        nlmDistanceDispatch_f32(
            temp0,
            castPtrs<const float>(centerp),
            castPtrs<const float>(neighborp),
            offset_x,
            offset_y,
            width,
            height,
            stride,
            channels
        );
    } else if (bits <= 8) {
        float inv_divisor = 1.0f / static_cast<float>((1 << bits) - 1);
        nlmDistanceDispatch_u8(
            temp0,
            castPtrs<const uint8_t>(centerp),
            castPtrs<const uint8_t>(neighborp),
            offset_x,
            offset_y,
            width,
            height,
            stride,
            channels,
            inv_divisor
        );
    } else if (bits <= 16) {
        float inv_divisor = 1.0f / static_cast<float>((1 << bits) - 1);
        nlmDistanceDispatch_u16(
            temp0,
            castPtrs<const uint16_t>(centerp),
            castPtrs<const uint16_t>(neighborp),
            offset_x,
            offset_y,
            width,
            height,
            stride,
            channels,
            inv_divisor
        );
    } else {
        assert(false);
    }
}

static inline void nlmAccumulationDispatch_f32(
    float* weightp,
    std::array<float*, 3> wdstp,
    float* max_weightp,
    std::array<const float*, 3> srcp_bwd,
    std::array<const float*, 3> srcp_fwd,
    const float* temp_bwd,
    const float* temp_fwd,
    int offset_x,
    int offset_y,
    int width,
    int height,
    int stride,
    ChannelMode channels
) noexcept {

    switch (channels) {
    case ChannelMode::Y:
        ispc::nlmAccumulationCh1_f32(
            weightp,
            wdstp[0],
            max_weightp,
            srcp_bwd[0],
            srcp_fwd[0],
            temp_bwd,
            temp_fwd,
            offset_x,
            offset_y,
            width,
            height,
            stride
        );
        break;
    case ChannelMode::UV:
        ispc::nlmAccumulationCh2_f32(
            weightp,
            wdstp[0],
            wdstp[1],
            max_weightp,
            srcp_bwd[1],
            srcp_bwd[2],
            srcp_fwd[1],
            srcp_fwd[2],
            temp_bwd,
            temp_fwd,
            offset_x,
            offset_y,
            width,
            height,
            stride
        );
        break;
    case ChannelMode::YUV:
    case ChannelMode::RGB:
        ispc::nlmAccumulationCh3_f32(
            weightp,
            wdstp[0],
            wdstp[1],
            wdstp[2],
            max_weightp,
            srcp_bwd[0],
            srcp_bwd[1],
            srcp_bwd[2],
            srcp_fwd[0],
            srcp_fwd[1],
            srcp_fwd[2],
            temp_bwd,
            temp_fwd,
            offset_x,
            offset_y,
            width,
            height,
            stride
        );
        break;
    }
}

static inline void nlmAccumulationDispatch_u8(
    float* weightp,
    std::array<float*, 3> wdstp,
    float* max_weightp,
    std::array<const uint8_t*, 3> srcp_bwd,
    std::array<const uint8_t*, 3> srcp_fwd,
    const float* temp_bwd,
    const float* temp_fwd,
    int offset_x,
    int offset_y,
    int width,
    int height,
    int stride,
    ChannelMode channels
) noexcept {

    switch (channels) {
    case ChannelMode::Y:
        ispc::nlmAccumulationCh1_u8(
            weightp,
            wdstp[0],
            max_weightp,
            srcp_bwd[0],
            srcp_fwd[0],
            temp_bwd,
            temp_fwd,
            offset_x,
            offset_y,
            width,
            height,
            stride
        );
        break;
    case ChannelMode::UV:
        ispc::nlmAccumulationCh2_u8(
            weightp,
            wdstp[0],
            wdstp[1],
            max_weightp,
            srcp_bwd[1],
            srcp_bwd[2],
            srcp_fwd[1],
            srcp_fwd[2],
            temp_bwd,
            temp_fwd,
            offset_x,
            offset_y,
            width,
            height,
            stride
        );
        break;
    case ChannelMode::YUV:
    case ChannelMode::RGB:
        ispc::nlmAccumulationCh3_u8(
            weightp,
            wdstp[0],
            wdstp[1],
            wdstp[2],
            max_weightp,
            srcp_bwd[0],
            srcp_bwd[1],
            srcp_bwd[2],
            srcp_fwd[0],
            srcp_fwd[1],
            srcp_fwd[2],
            temp_bwd,
            temp_fwd,
            offset_x,
            offset_y,
            width,
            height,
            stride
        );
        break;
    }
}

static inline void nlmAccumulationDispatch_u16(
    float* weightp,
    std::array<float*, 3> wdstp,
    float* max_weightp,
    std::array<const uint16_t*, 3> srcp_bwd,
    std::array<const uint16_t*, 3> srcp_fwd,
    const float* temp_bwd,
    const float* temp_fwd,
    int offset_x,
    int offset_y,
    int width,
    int height,
    int stride,
    ChannelMode channels
) noexcept {

    switch (channels) {
    case ChannelMode::Y:
        ispc::nlmAccumulationCh1_u16(
            weightp,
            wdstp[0],
            max_weightp,
            srcp_bwd[0],
            srcp_fwd[0],
            temp_bwd,
            temp_fwd,
            offset_x,
            offset_y,
            width,
            height,
            stride
        );
        break;
    case ChannelMode::UV:
        ispc::nlmAccumulationCh2_u16(
            weightp,
            wdstp[0],
            wdstp[1],
            max_weightp,
            srcp_bwd[1],
            srcp_bwd[2],
            srcp_fwd[1],
            srcp_fwd[2],
            temp_bwd,
            temp_fwd,
            offset_x,
            offset_y,
            width,
            height,
            stride
        );
        break;
    case ChannelMode::YUV:
    case ChannelMode::RGB:
        ispc::nlmAccumulationCh3_u16(
            weightp,
            wdstp[0],
            wdstp[1],
            wdstp[2],
            max_weightp,
            srcp_bwd[0],
            srcp_bwd[1],
            srcp_bwd[2],
            srcp_fwd[0],
            srcp_fwd[1],
            srcp_fwd[2],
            temp_bwd,
            temp_fwd,
            offset_x,
            offset_y,
            width,
            height,
            stride
        );
        break;
    }
}

static inline void nlmAccumulation(
    float* weightp,
    std::array<float*, 3> wdstp,
    float* max_weightp,
    std::array<const void*, 3> srcp_bwd,
    std::array<const void*, 3> srcp_fwd,
    const float* temp_bwd,
    const float* temp_fwd,
    int offset_x,
    int offset_y,
    int width,
    int height,
    int stride,
    ChannelMode channels,
    int bits
) noexcept {

    if (bits == 32) {
        nlmAccumulationDispatch_f32(
            weightp,
            wdstp,
            max_weightp,
            castPtrs<const float>(srcp_bwd),
            castPtrs<const float>(srcp_fwd),
            temp_bwd,
            temp_fwd,
            offset_x,
            offset_y,
            width,
            height,
            stride,
            channels
        );
    } else if (bits <= 8) {
        nlmAccumulationDispatch_u8(
            weightp,
            wdstp,
            max_weightp,
            castPtrs<const uint8_t>(srcp_bwd),
            castPtrs<const uint8_t>(srcp_fwd),
            temp_bwd,
            temp_fwd,
            offset_x,
            offset_y,
            width,
            height,
            stride,
            channels
        );
    } else if (bits <= 16) {
        nlmAccumulationDispatch_u16(
            weightp,
            wdstp,
            max_weightp,
            castPtrs<const uint16_t>(srcp_bwd),
            castPtrs<const uint16_t>(srcp_fwd),
            temp_bwd,
            temp_fwd,
            offset_x,
            offset_y,
            width,
            height,
            stride,
            channels
        );
    } else {
        assert(false);
    }
}

static inline void nlmFinishDispatch_f32(
    std::array<float*, 3> dstp,
    std::array<const float*, 3> srcp,
    const float* weightp,
    std::array<float*, 3> wdstp,
    const float* max_weightp,
    float wref,
    int width,
    int height,
    int stride,
    ChannelMode channels
) noexcept {

    switch (channels) {
    case ChannelMode::Y:
        ispc::nlmFinishCh1_f32(dstp[0], srcp[0], weightp, wdstp[0], max_weightp, wref, width, height, stride);
        break;
    case ChannelMode::UV:
        ispc::nlmFinishCh2_f32(
            dstp[1], dstp[2], srcp[1], srcp[2], weightp, wdstp[0], wdstp[1], max_weightp, wref, width, height, stride
        );
        break;
    case ChannelMode::YUV:
    case ChannelMode::RGB:
        ispc::nlmFinishCh3_f32(
            dstp[0],
            dstp[1],
            dstp[2],
            srcp[0],
            srcp[1],
            srcp[2],
            weightp,
            wdstp[0],
            wdstp[1],
            wdstp[2],
            max_weightp,
            wref,
            width,
            height,
            stride
        );
        break;
    }
}

static inline void nlmFinishDispatch_u8(
    std::array<uint8_t*, 3> dstp,
    std::array<const uint8_t*, 3> srcp,
    const float* weightp,
    std::array<float*, 3> wdstp,
    const float* max_weightp,
    float wref,
    int width,
    int height,
    int stride,
    ChannelMode channels,
    int peak
) noexcept {

    switch (channels) {
    case ChannelMode::Y:
        ispc::nlmFinishCh1_u8(dstp[0], srcp[0], weightp, wdstp[0], max_weightp, wref, width, height, stride, peak);
        break;
    case ChannelMode::UV:
        ispc::nlmFinishCh2_u8(
            dstp[1],
            dstp[2],
            srcp[1],
            srcp[2],
            weightp,
            wdstp[0],
            wdstp[1],
            max_weightp,
            wref,
            width,
            height,
            stride,
            peak
        );
        break;
    case ChannelMode::YUV:
    case ChannelMode::RGB:
        ispc::nlmFinishCh3_u8(
            dstp[0],
            dstp[1],
            dstp[2],
            srcp[0],
            srcp[1],
            srcp[2],
            weightp,
            wdstp[0],
            wdstp[1],
            wdstp[2],
            max_weightp,
            wref,
            width,
            height,
            stride,
            peak
        );
        break;
    }
}

static inline void nlmFinishDispatch_u16(
    std::array<uint16_t*, 3> dstp,
    std::array<const uint16_t*, 3> srcp,
    const float* weightp,
    std::array<float*, 3> wdstp,
    const float* max_weightp,
    float wref,
    int width,
    int height,
    int stride,
    ChannelMode channels,
    int peak
) noexcept {

    switch (channels) {
    case ChannelMode::Y:
        ispc::nlmFinishCh1_u16(dstp[0], srcp[0], weightp, wdstp[0], max_weightp, wref, width, height, stride, peak);
        break;
    case ChannelMode::UV:
        ispc::nlmFinishCh2_u16(
            dstp[1],
            dstp[2],
            srcp[1],
            srcp[2],
            weightp,
            wdstp[0],
            wdstp[1],
            max_weightp,
            wref,
            width,
            height,
            stride,
            peak
        );
        break;
    case ChannelMode::YUV:
    case ChannelMode::RGB:
        ispc::nlmFinishCh3_u16(
            dstp[0],
            dstp[1],
            dstp[2],
            srcp[0],
            srcp[1],
            srcp[2],
            weightp,
            wdstp[0],
            wdstp[1],
            wdstp[2],
            max_weightp,
            wref,
            width,
            height,
            stride,
            peak
        );
        break;
    }
}

static inline void nlmFinish(
    std::array<void*, 3> dstp,
    std::array<const void*, 3> srcp,
    const float* weightp,
    std::array<float*, 3> wdstp,
    const float* max_weightp,
    float wref,
    int width,
    int height,
    int stride,
    ChannelMode channels,
    int bits
) noexcept {

    if (bits == 32) {
        nlmFinishDispatch_f32(
            castPtrs<float>(dstp),
            castPtrs<const float>(srcp),
            weightp,
            wdstp,
            max_weightp,
            wref,
            width,
            height,
            stride,
            channels
        );
    } else if (bits <= 8) {
        int peak = (1 << bits) - 1;
        nlmFinishDispatch_u8(
            castPtrs<uint8_t>(dstp),
            castPtrs<const uint8_t>(srcp),
            weightp,
            wdstp,
            max_weightp,
            wref,
            width,
            height,
            stride,
            channels,
            peak
        );
    } else if (bits <= 16) {
        int peak = (1 << bits) - 1;
        nlmFinishDispatch_u16(
            castPtrs<uint16_t>(dstp),
            castPtrs<const uint16_t>(srcp),
            weightp,
            wdstp,
            max_weightp,
            wref,
            width,
            height,
            stride,
            channels,
            peak
        );
    } else {
        assert(false);
    }
}

static const VSFrame* VS_CC nlmGetFrame(
    int n,
    int activationReason,
    void* instanceData,
    void** frameData,
    VSFrameContext* frameCtx,
    VSCore* core,
    const VSAPI* vsapi
) noexcept {

    auto* d = reinterpret_cast<NLMData*>(instanceData);

    if (activationReason == arInitial) {
        int start = std::max(0, n - d->d);
        int end = std::min(n + d->d, d->vi->numFrames - 1);
        for (int i = start; i <= end; i++) {
            vsapi->requestFrameFilter(i, d->node, frameCtx);
            if (d->ref_node) {
                vsapi->requestFrameFilter(i, d->ref_node, frameCtx);
            }
        }
        return nullptr;
    }
    if (activationReason != arAllFramesReady) {
        return nullptr;
    }

    // activationReason == arAllFramesReady

    int nlm_d = d->d;
    int nlm_a = d->a;
    int nlm_s = d->s;
    float nlm_h2_inv_norm = d->h2_inv_norm;
    float nlm_wref = d->wref;
    ChannelMode channels = d->channels;

    const auto& ref_node = d->ref_node ? d->ref_node : d->node;
    const auto* ref_frame = vsapi->getFrameFilter(n, ref_node, frameCtx);

    int bits = d->vi->format.bitsPerSample;
    int width = 0;
    int height = 0;
    int stride = 0; // dimensions of the plane to be processed, not the video dimension
    if (channels == ChannelMode::UV) {
        width = d->vi->width >> d->vi->format.subSamplingW;
        height = d->vi->height >> d->vi->format.subSamplingH;
        stride = static_cast<int>(vsapi->getStride(ref_frame, 1) / d->vi->format.bytesPerSample);
    } else {
        width = d->vi->width;
        height = d->vi->height;
        stride = static_cast<int>(vsapi->getStride(ref_frame, 0) / d->vi->format.bytesPerSample);
    }

    int size = height * stride; // size of each plane in quad-bytes
    // number of input channels
    int num_input_channels = [channels]() {
        if (channels == ChannelMode::Y) {
            return 1;
        }
        if (channels == ChannelMode::UV) {
            return 2;
        }
        return 3;
    }();
    // size in quad-bytes: size * (4 + num_input_channels + (nlm_d != 0)) + width
    float* workspace = nullptr;
    {
        auto thread_id = std::this_thread::get_id();
        {
            std::shared_lock lock{d->workspaces_lock};
            auto it = d->workspaces.find(thread_id);
            if (it != d->workspaces.end()) {
                workspace = it->second;
            }
        }

        if (!workspace) {
            auto workspace_size = size * (4 + num_input_channels + (nlm_d != 0)) + width;
            auto workspace_bytes = workspace_size * sizeof(float);
            workspace = vsh::vsh_aligned_malloc<float>(workspace_bytes, 256);

            if (!workspace) {
                vsapi->freeFrame(ref_frame);
                vsapi->setFilterError("nlm_ispc: malloc() failed", frameCtx);
                return nullptr;
            }

            std::unique_lock lock{d->workspaces_lock};
            d->workspaces[thread_id] = workspace;
        }
    }

    const auto size_offset = static_cast<std::size_t>(size);

    // zero-initialize aggregation buffers
    std::memset(workspace, 0, (1 + num_input_channels) * size_offset * sizeof(float));
    // stores the sum of weights of each pixel
    float* weightp = workspace;
    std::array<float*, 3> wdstp{
        // stores the weighted sum of pixel values of the first processed plane
        workspace + size_offset,
        // stores the weighted sum of pixel values of the second processed plane
        num_input_channels <= 1 ? nullptr : workspace + 2 * size_offset,
        // stores the weighted sum of pixel values of the third processed plane
        num_input_channels <= 2 ? nullptr : workspace + 3 * size_offset
    };

    // stores the maximum weight encountered of each pixel
    float* max_weightp = workspace + (1 + num_input_channels) * size_offset;
    std::fill_n(max_weightp, size, std::numeric_limits<float>::epsilon());

    // temporary storage for the calculation of patch distances
    float* temp = workspace + (2 + num_input_channels) * size_offset;
    float* temp_bwd = workspace + (3 + num_input_channels) * size_offset;
    float* temp_fwd = nlm_d == 0 ? nullptr : workspace + (4 + num_input_channels) * size_offset;

    // buffer for the vertical box filter during patch distance calculation
    // size in quad-bytes: width
    float* buffer = workspace + (4 + num_input_channels + (nlm_d != 0)) * size_offset;

    std::array refp{getPtrs(ref_frame, channels, vsapi)};

    for (int i = -nlm_d; i <= 0; i++) {
        auto bwd_n = std::max(n + i, 0);
        auto fwd_n = std::min(n - i, d->vi->numFrames - 1);
        const auto* src_frame_bwd = vsapi->getFrameFilter(bwd_n, d->node, frameCtx);
        const auto* src_frame_fwd = vsapi->getFrameFilter(fwd_n, d->node, frameCtx);
        const auto* ref_frame_bwd = vsapi->getFrameFilter(bwd_n, ref_node, frameCtx);
        const auto* ref_frame_fwd = vsapi->getFrameFilter(fwd_n, ref_node, frameCtx);

        std::array srcp_bwd{getPtrs(src_frame_bwd, channels, vsapi)};
        std::array srcp_fwd{getPtrs(src_frame_fwd, channels, vsapi)};
        std::array refp_bwd{getPtrs(ref_frame_bwd, channels, vsapi)};
        std::array refp_fwd{getPtrs(ref_frame_fwd, channels, vsapi)};

        for (int offset_y = -nlm_a; offset_y <= nlm_a; offset_y++) {
            for (int offset_x = -nlm_a; offset_x <= nlm_a; offset_x++) {
                if (i * square(2 * nlm_a + 1) + offset_y * (2 * nlm_a + 1) + offset_x >= 0) {
                    continue;
                }

                nlmDistance(temp_bwd, refp, refp_bwd, offset_x, offset_y, width, height, stride, channels, bits);

                ispc::nlmHorizontal(temp, temp_bwd, nlm_s, width, height, stride);

                d->nlm_vertical(temp_bwd, temp, nlm_s, nlm_h2_inv_norm, width, height, stride, buffer);

                // jump at the end of this basic block
                if (i == 0) {
                    // bwd == fwd
                    nlmAccumulation(
                        weightp,
                        wdstp,
                        max_weightp,
                        srcp_bwd,
                        srcp_bwd,
                        temp_bwd,
                        temp_bwd,
                        offset_x,
                        offset_y,
                        width,
                        height,
                        stride,
                        channels,
                        bits
                    );
                    continue;
                }

                // i != 0
                nlmDistance(temp_fwd, refp_fwd, refp, offset_x, offset_y, width, height, stride, channels, bits);

                ispc::nlmHorizontal(temp, temp_fwd, nlm_s, width, height, stride);

                d->nlm_vertical(temp_fwd, temp, nlm_s, nlm_h2_inv_norm, width, height, stride, buffer);

                nlmAccumulation(
                    weightp,
                    wdstp,
                    max_weightp,
                    srcp_bwd,
                    srcp_fwd,
                    temp_bwd,
                    temp_fwd,
                    offset_x,
                    offset_y,
                    width,
                    height,
                    stride,
                    channels,
                    bits
                );
            }
        }

        vsapi->freeFrame(src_frame_fwd);
        vsapi->freeFrame(src_frame_bwd);
        vsapi->freeFrame(ref_frame_fwd);
        vsapi->freeFrame(ref_frame_bwd);
    }

    vsapi->freeFrame(ref_frame);

    const auto* src_frame = vsapi->getFrameFilter(n, d->node, frameCtx);
    std::array srcp{getPtrs(src_frame, channels, vsapi)};

    VSFrame* dst_frame = nullptr;
    if (channels == ChannelMode::Y && d->vi->format.numPlanes > 1) {
        const VSFrame* fr[3]{nullptr, src_frame, src_frame};
        constexpr int pl[3]{0, 1, 2};
        dst_frame = vsapi->newVideoFrame2(&d->vi->format, d->vi->width, d->vi->height, fr, pl, src_frame, core);
    } else if (channels == ChannelMode::UV && d->vi->format.numPlanes > 1) {
        const VSFrame* fr[3]{src_frame, nullptr, nullptr};
        constexpr int pl[3]{0, 1, 2};
        dst_frame = vsapi->newVideoFrame2(&d->vi->format, d->vi->width, d->vi->height, fr, pl, src_frame, core);
    } else {
        dst_frame = vsapi->newVideoFrame(&d->vi->format, d->vi->width, d->vi->height, src_frame, core);
    }
    std::array dstp{getPtrs(dst_frame, channels, vsapi)};

    nlmFinish(dstp, srcp, weightp, wdstp, max_weightp, nlm_wref, width, height, stride, channels, bits);

    vsapi->freeFrame(src_frame);

    return dst_frame;
}

static void VS_CC nlmFree(void* instanceData, VSCore* core, const VSAPI* vsapi) noexcept {

    auto* d = reinterpret_cast<NLMData*>(instanceData);

    vsapi->freeNode(d->node);
    if (d->ref_node) {
        vsapi->freeNode(d->ref_node);
    }

    for (const auto& [_, ptr] : d->workspaces) {
        vsh::vsh_aligned_free(ptr);
    }

    delete d;
}

static void VS_CC nlmCreate(const VSMap* in, VSMap* out, void* userData, VSCore* core, const VSAPI* vsapi) noexcept {

    auto d = std::make_unique<NLMData>();

    d->node = vsapi->mapGetNode(in, "clip", 0, nullptr);
    d->vi = vsapi->getVideoInfo(d->node);

    auto set_error = [vsapi, out, &d](const char* error_message) -> void {
        vsapi->mapSetError(out, error_message);
        vsapi->freeNode(d->node);
    };

    if (!vsh::isConstantVideoFormat(d->vi)) {
        return set_error("only constant video format supported");
    }

    if ((d->vi->format.sampleType == stInteger && d->vi->format.bitsPerSample > 16) ||
        (d->vi->format.sampleType == stFloat && d->vi->format.bitsPerSample != 32)) {
        return set_error("only 1-16 bit integer or 32-bit float supported");
    }

    int err = 0;

    d->d = vsh::int64ToIntS(vsapi->mapGetInt(in, "d", 0, &err));
    if (err) {
        d->d = 1;
    }
    if (d->d < 0) {
        return set_error("\"d\" must be non-negative");
    }

    d->a = vsh::int64ToIntS(vsapi->mapGetInt(in, "a", 0, &err));
    if (err) {
        d->a = 2;
    }
    if (d->a <= 0) {
        return set_error("\"a\" must be positive");
    }

    d->s = vsh::int64ToIntS(vsapi->mapGetInt(in, "s", 0, &err));
    if (err) {
        d->s = 4;
    }
    if (d->s < 0) {
        return set_error("\"s\" must be non-negative");
    }

    d->h = static_cast<float>(vsapi->mapGetFloat(in, "h", 0, &err));
    if (err) {
        d->h = 1.2f;
    }
    if (d->h <= 0.0f) {
        return set_error("\"h\" must be positive");
    }

    d->h2_inv_norm = square(255.0f) / (3.0f * square(d->h) * square(static_cast<float>(2 * d->s + 1)));

    auto wmode = vsapi->mapGetInt(in, "wmode", 0, &err);
    if (err) {
        wmode = 0;
    }
    if (wmode < 0 || wmode > 3) {
        return set_error("\"wmode\" must be 0, 1, 2 or 3");
    }
    decltype(d->nlm_vertical) nlmVerticalKernels[]{
        &ispc::nlmVerticalWelsch, &ispc::nlmVerticalBisquareA, &ispc::nlmVerticalBisquareB, &ispc::nlmVerticalBisquareC
    };
    d->nlm_vertical = nlmVerticalKernels[wmode];

    const auto* channels_raw = vsapi->mapGetData(in, "channels", 0, &err);
    std::string_view channels = err ? "AUTO" : channels_raw;
    if (channels == "Y") {
        d->channels = ChannelMode::Y;
    } else if (channels == "UV") {
        d->channels = ChannelMode::UV;
    } else if (channels == "YUV") {
        d->channels = ChannelMode::YUV;
    } else if (channels == "RGB") {
        d->channels = ChannelMode::RGB;
    } else if (channels == "AUTO") {
        if (d->vi->format.colorFamily == cfRGB) {
            d->channels = ChannelMode::RGB;
        } else {
            d->channels = ChannelMode::Y;
        }
    } else {
        return set_error("\"channels\" must be \"Y\", \"UV\", \"YUV\", \"RGB\" or \"AUTO\"");
    }

    if (d->channels == ChannelMode::Y) {
        if (d->vi->format.colorFamily != cfGray && d->vi->format.colorFamily != cfYUV) {
            return set_error("color family must be Gray or YUV for \"channels\" == \"Y\"");
        }
    } else if (d->channels == ChannelMode::UV) {
        if (d->vi->format.colorFamily != cfYUV) {
            return set_error("color family must be YUV for \"channels\" == \"UV\"");
        }
    } else if (d->channels == ChannelMode::YUV) {
        if (d->vi->format.colorFamily != cfYUV || d->vi->format.subSamplingW || d->vi->format.subSamplingH) {
            return set_error("color family must be YUV444 for \"channels\" == \"YUV\"");
        }
    } else if (d->channels == ChannelMode::RGB) {
        if (d->vi->format.colorFamily != cfRGB) {
            return set_error("color family must be RGB for \"channels\" == \"RGB\"");
        }
    }

    d->wref = static_cast<float>(vsapi->mapGetFloat(in, "wref", 0, &err));
    if (err) {
        d->wref = 1.0f;
    }

    d->ref_node = vsapi->mapGetNode(in, "rclip", 0, &err);
    if (err) {
        d->ref_node = nullptr;
    }
    if (d->ref_node) {
        const auto* const ref_vi = vsapi->getVideoInfo(d->ref_node);
        if (!vsh::isSameVideoInfo(d->vi, ref_vi) || d->vi->numFrames != ref_vi->numFrames) {
            vsapi->freeNode(d->ref_node);
            return set_error("\"rclip\" must be of the same format as \"clip\"");
        }
    }

    VSCoreInfo core_info;
    vsapi->getCoreInfo(core, &core_info);
    d->workspaces.reserve(core_info.numThreads);

    auto* data = d.release();

    VSFilterDependency deps[] = {
        {.source = data->node, .requestPattern = data->d == 0 ? rpStrictSpatial : rpGeneral},
        {.source = data->ref_node, .requestPattern = data->d == 0 ? rpStrictSpatial : rpGeneral}
    };

    vsapi->createVideoFilter(
        out, "NLMeans", data->vi, nlmGetFrame, nlmFree, fmParallel, deps, data->ref_node ? 2 : 1, data, core
    );
}

VS_EXTERNAL_API(void) VapourSynthPluginInit2(VSPlugin* plugin, const VSPLUGINAPI* vspapi) noexcept {

    vspapi->configPlugin(
        "io.github.amusementclub.vs-nlm-ispc",
        "nlm_ispc",
        "Non-local means denoise filter implemented in ISPC",
        VS_MAKE_VERSION(0, 1),
        VAPOURSYNTH_API_VERSION,
        0,
        plugin
    );

    vspapi->registerFunction(
        "NLMeans",
        "clip:vnode;"
        "d:int:opt;"
        "a:int:opt;"
        "s:int:opt;"
        "h:float:opt;"
        "channels:data:opt;"
        "wmode:int:opt;"
        "wref:float:opt;"
        "rclip:vnode:opt;",
        "clip:vnode;",
        nlmCreate,
        nullptr,
        plugin
    );

    auto getVersion = [](const VSMap *, VSMap *out, void *, VSCore *, const VSAPI *vsapi) {
        vsapi->mapSetData(out, "version", VERSION, -1, dtUtf8, maReplace);
    };
    vspapi->registerFunction("Version", "", "version:data;", getVersion, nullptr, plugin);
}
